
[font]
normal = { family = "Anonymous Pro" }
# size = 11.0

[env]
TERM = "xterm-256color"

[keyboard]
bindings = [{ key = "N", mods = "Shift|Control", action = "CreateNewWindow" },]

[general]
import = [
    "~/.config/alacritty/themes/hyper.toml"
]
